name: macOS workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build app
        run: make
      #- name: Run tests
      #  run: make clt_tests
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with: 
          name: Platypus
          path: products
